export const DEMO_ROUTES = [
  "/",
  "/accept/high-risk-processing",
  "/industries",
  "/industries/nutra-supplements",
  "/partners/isos-agents",
  "/live-form",
  // Company and Resources pages (D-054).
  "/about-beyond-bancard",
  "/careers",
  "/contact-us",
  "/news",
  "/news/what-is-a-high-risk-merchant-account-and-how-does-it-work",
  "/our-clients",
  "/faq",
  // First page of the Industries and Partners menus (D-057).
  "/industries/adult",
  "/partners",
  // Top 6 industries and every Solutions page (D-058).
  "/industries/gaming",
  "/industries/ruo-peptides",
  "/industries/travel-payment-solutions",
  "/industries/crb",
  "/accept",
  "/accept/online-payments",
  "/accept/in-person-payments",
  "/accept/b2b-payments",
  "/accept/international-payments",
  "/accept/ach-echeck",
  "/protect",
  "/protect/chargeback-protection",
  "/protect/network-tokenization",
  "/protect/3d-secure",
  "/protect/fraud-risk-tools",
  "/grow",
  "/grow/working-capital",
  "/grow/instant-payouts",
  "/grow/recurring-billing",
  "/grow/cost-reduction-programs",
  "/operate",
  "/operate/dashboard-reporting",
  "/operate/invoicing",
  "/operate/payment-gateways",
  "/operate/payment-technology",
  "/operate/pos",
  "/operate/virtual-terminal",
  // The last two Partners menu pages (D-061).
  "/partners/isvs-platforms",
  "/partners/associations",
  // Legal pages (D-062).
  "/terms-conditions",
  "/privacy-policy",
  "/accessibility",
] as const;
