import {
  Activity,
  ArrowLeftRight,
  BadgeCheck,
  Banknote,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  ChartNoAxesColumn,
  Clock,
  Coins,
  CreditCard,
  Eye,
  FileSearch,
  FileText,
  Gauge,
  Globe,
  Handshake,
  Headset,
  KeyRound,
  Landmark,
  Laptop,
  Layers,
  Link,
  Lock,
  MapPin,
  Megaphone,
  Monitor,
  Package,
  Percent,
  Plug,
  Receipt,
  Repeat,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Store,
  Tag,
  TrendingUp,
  TriangleAlert,
  Truck,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/types/content";

const map: Record<IconName, LucideIcon> = {
  store: Store,
  laptop: Laptop,
  repeat: Repeat,
  receipt: Receipt,
  "file-search": FileSearch,
  globe: Globe,
  layers: Layers,
  shield: ShieldCheck,
  users: Users,
  wallet: Wallet,
  headset: Headset,
  clock: Clock,
  sliders: SlidersHorizontal,
  "badge-check": BadgeCheck,
  megaphone: Megaphone,
  "trending-up": TrendingUp,
  package: Package,
  handshake: Handshake,
  briefcase: Briefcase,
  "credit-card": CreditCard,
  chart: ChartNoAxesColumn,
  activity: Activity,
  lock: Lock,
  key: KeyRound,
  landmark: Landmark,
  banknote: Banknote,
  smartphone: Smartphone,
  monitor: Monitor,
  calendar: Calendar,
  zap: Zap,
  link: Link,
  percent: Percent,
  "file-text": FileText,
  building: Building2,
  truck: Truck,
  alert: TriangleAlert,
  eye: Eye,
  gauge: Gauge,
  plug: Plug,
  tag: Tag,
  calculator: Calculator,
  coins: Coins,
  "map-pin": MapPin,
  arrows: ArrowLeftRight,
};

/** Content-driven icon lookup so content files stay serialisable. */
export function Icon({ name, className }: { name: IconName; className?: string }) {
  const C = map[name];
  return <C aria-hidden strokeWidth={1.75} className={className ?? "size-6"} />;
}
