// Generates docs/CONFIRM_LIST.md from every CONFIRM flag in the codebase:
// - `<Confirm note="...">` usages in components and pages
// - content objects with `confirm: true` and a `note`
// Run: pnpm confirm-list
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOTS = ["app", "components", "content"];
const entries = [];

function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = path.join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(tsx?|mts)$/.test(name)) scan(p);
  }
}

function scan(file) {
  const src = readFileSync(file, "utf8");
  const rel = file.replaceAll("\\", "/");
  if (rel.includes("components/ui/confirm.tsx") || rel.includes("app/dev/")) return;
  const lines = src.split("\n");

  lines.forEach((line, i) => {
    // <Confirm note="...">  (static string notes only; dynamic notes come from content)
    const jsx = line.match(/<Confirm[^>]*\snote="([^"]+)"/);
    if (jsx) entries.push({ note: jsx[1], file: rel, line: i + 1 });

    // confirm: true ... note: "..." on the same or following lines
    if (/confirm:\s*true/.test(line)) {
      const windowText = lines.slice(i, i + 4).join(" ");
      const m = windowText.match(/note:\s*(["'`])((?:\\.|(?!\1).)*)\1/);
      if (m) entries.push({ note: m[2].replace(/\\"/g, '"'), file: rel, line: i + 1 });
    }
  });

  // Named note fields used by dedicated Confirm wrappers (announcement, apply lead, testimonials)
  const named = [...src.matchAll(/^\s*(?:export const )?(\w*[nN]ote)\s*[:=]\s*"([^"]+)"/gm)];
  for (const m of named) {
    if (m[1] === "note" && /confirm:\s*true/.test(src.slice(Math.max(0, m.index - 200), m.index))) continue;
    const line = src.slice(0, m.index).split("\n").length;
    if (!entries.some((e) => e.file === rel && e.line === line)) entries.push({ note: m[2], file: rel, line });
  }
}

ROOTS.forEach(walk);

// Group identical notes so the client answers each question once.
const byNote = new Map();
for (const e of entries) {
  const list = byNote.get(e.note) ?? [];
  list.push(`${e.file}:${e.line}`);
  byNote.set(e.note, list);
}

const open = [
  "Official logo files (primary, reversed, one-colour) and brand blue hex (\"Primary_Logo_Blue_Punchout\")",
  "Brand fonts, if any (currently Archivo + IBM Plex Sans)",
  "Licensed logo usage for gateways and sponsor banks (shown as text today)",
  "Apply form required fields (must match the onboarding system)",
  "Drafted supporting copy listed in docs/DECISIONS.md (D-011)",
  "Footer wordmark lockup: \"Beyond Bancard.\" with a brand-blue full stop (D-053)",
];

const md = [
  "# CONFIRM list",
  "",
  "Everything below renders with a dashed amber outline in demo mode (`NEXT_PUBLIC_DEMO_MODE=true`) and is hidden in production until confirmed.",
  "Generated by `pnpm confirm-list` — do not edit by hand.",
  "",
  "## Flagged content",
  "",
  "| # | Client to confirm | Where |",
  "|---|---|---|",
  ...[...byNote.entries()].map(([note, where], i) => `| ${i + 1} | ${note.replaceAll("|", "\\|")} | ${where.map((w) => `\`${w}\``).join("<br>")} |`),
  "",
  "## Open questions (not flagged in the UI)",
  "",
  ...open.map((o) => `- [ ] ${o}`),
  "",
].join("\n");

writeFileSync("docs/CONFIRM_LIST.md", md);
console.log(`CONFIRM_LIST.md: ${byNote.size} unique items from ${entries.length} usages`);
